const DIAGRAMS = [
  "flowchart TD\n  A[Markdown] --> B[Mermaid]\n  B --> C[Parse]\n  C --> D[SVG]",
  "graph LR\n  Start((Start)) --> Check{Small?}\n  Check -->|yes| Ship[Ship]\n  Check -->|no| Tune[Optimize]",
  "sequenceDiagram\n  User->>Renderer: input\n  Renderer-->>User: svg",
  "classDiagram\n  Diagram <|-- Flowchart\n  Diagram : +render()\n  Flowchart : +layout()",
  "stateDiagram-v2\n  [*] --> Draft\n  Draft --> Tested: bun test\n  Tested --> Shipped",
  "flowchart TD\n  Repo[External Repos] --> Extract[Extract Tests]\n  Extract --> Yml[test/*.yml]\n  Yml --> Bun[Bun Test]",
  "flowchart LR\n  Code[Source] --> Minify[Rolldown]\n  Minify --> Lib[lib/svg.js]\n  Lib --> Gzip[GZIP]",
  "sequenceDiagram\n  Cursor->>Loop: next task\n  Loop->>Test: run checks\n  Test-->>Loop: result\n  Loop-->>Cursor: summary",
  "graph TD\n  Fast[Fast Path] --> String[String SVG]\n  String --> NoDom[No DOM]\n  NoDom --> Tiny[Tiny Bundle]",
  "flowchart LR\n  Theme[Theme Button] --> Mint[Mint]\n  Theme --> Light[Light]\n  Theme --> Dark[Dark]",
  "sequenceDiagram\n  Cloudflare->>Demo: deploy\n  Demo-->>User: static site",
  "graph TD\n  A[Input] --> B{Diagram Type}\n  B --> Flow[Flowchart]\n  B --> Seq[Sequence]\n  B --> State[State]",
  "flowchart TD\n  Mermaid[Mermaid Text] --> AST[AST]\n  AST --> Layout[Layout]\n  Layout --> Render[SVG Render]",
  "classDiagram\n  Renderer <|-- FlowRenderer\n  Renderer <|-- SequenceRenderer",
  "stateDiagram-v2\n  [*] --> Parse\n  Parse --> Layout\n  Layout --> Render\n  Render --> [*]",
  "graph LR\n  Maid[maid] --> Cases[Cases]\n  Beautiful[beautiful-mermaid] --> Cases\n  Mermaid[mermaid] --> Cases",
  "flowchart TD\n  Tiny[Small Code] --> Fast[Fast Render]\n  Fast --> Pretty[Pretty SVG]",
  "sequenceDiagram\n  Dev->>AI: prompt loop\n  AI->>Repo: patch\n  Repo-->>Dev: diff",
  "graph LR\n  SVG[SVG] --> Copy[Copy]\n  SVG --> Preview[Preview]\n  SVG --> Deploy[Deploy]",
  "flowchart TD\n  A[Node] --> B[Edge Label]\n  B -->|label| C[Target]",
  "classDiagram\n  Theme <|-- Light\n  Theme <|-- Mint\n  Theme <|-- Dark",
  "stateDiagram-v2\n  Idle --> Typing\n  Typing --> Preview\n  Preview --> Typing",
  "graph TD\n  Build[Build] --> Size[Size Chart]\n  Build --> Speed[Speed Bench]",
  "sequenceDiagram\n  Browser->>SVG: paint\n  SVG-->>Browser: native shapes",
  "flowchart LR\n  YAML[YAML] --> Compare[Compare]\n  Compare --> Pass[Pass]",
  "graph TD\n  CDN[beautiful-mermaid CDN] --> Compare[Size Compare]\n  Ours[Our gzip] --> Compare",
  "classDiagram\n  Extractor <|-- RepoScanner\n  Extractor <|-- Filter",
  "stateDiagram-v2\n  New --> Supported\n  Supported --> Snapshot\n  Snapshot --> Regression",
  "graph LR\n  I18n[76 Languages] --> Demo\n  Demo --> Cloudflare",
  "sequenceDiagram\n  User->>Theme: click\n  Theme-->>Preview: rerender",
  "flowchart TD\n  Source[src/svg.js] --> Test[test/*.yml]\n  Test --> Demo[demo]",
  "graph LR\n  Minimal[Minimal] --> Fastest[Fastest]\n  Fastest --> MermaidSVG[Mermaid SVG]",
];

export default DIAGRAMS;
